[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[stackbit]
  deployCommand = "npm run build"
  buildCommand = "npm run build"
  devCommand = "npm run dev"
  containerPort = 8080